### ISSUE TITLE
Doesn't compile on my windows

### ISSUE THREAD

**Issue by adsick** [Wumpf/blub#39]
cargo run results in the following:
The following warnings were emitted during compilation:

warning: System installed library not found.  Falling back to build from source

error: failed to run custom build command for `shaderc-sys v0.6.3`

Caused by:
  process didn't exit successfully: `C:\Users\vadim\Downloads\blub-master\blub-master\target\debug\build\shaderc-sys-ad6ce452982fe3d6\build-script-build` (exit code: 101)
  --- stdout
  cargo:warning=System installed library not found.  Falling back to build from source

  --- stderr
  thread 'main' panicked at '

  couldn't find required command: "cmake"

  ', C:\Users\vadim\.cargo\registry\src\github.com-1ecc6299db9ec823\shaderc-sys-0.6.3\build\cmd_finder.rs:50:13
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: build failed

**Comment by corjohnson** [comment]
You might have to install cmake in order to build anything using shaderc; I'm pretty sure that's a dependency of it

**Comment by adsick** [comment]
Omg, man, I installed cmake, then the compilation process exited with error saying that git command not found, so I installed git. Now it says that python is missing. Can you just mention all the deps so I don't need to compile over and over again

**Comment by adsick** [comment]
So now after 3 restarts it also requires some "ninja"... man, I leave

**Comment by Wumpf** [comment]
Yes these are all dependencies of `shaderc`. See:
https://github.com/google/shaderc-rs#building-from-source
Quite unfortunate, without that it would be a simple matter of `cargo run`. I'll leave a note in the Readme!

**Comment by adsick** [comment]
Ok, good. It would be really nice to build everything using just simple cargo run, but looks like it is not there yet. Imma newcomer and this is a bit irritating
