### ISSUE TITLE
Add git LFS as dependencies

### ISSUE THREAD

**Issue by pannapudi** [Wumpf/blub#40]
Git LFS is not supplied by default by some package managers. Mention in the readme that the LSF subcommand must be installed to upload background images.

P.S.: Works fine on linux. 3-5 fps on weak GeForce MX130

**Comment by corjohnson** [comment]
Why does this need git LFS?

**Comment by pannapudi** [comment]
For downloading /background/*.hdr files.

**Comment by Wumpf** [comment]
oh nice to hear it still runs "fine" on older mid range mobile gpus. In the future I may do more optimizations and provide scenes that are easier to swallow for weaker gpus. I'm running myself everything on a gtx1070 which gives me currently 10-40 fps depending on what's on screen and what new thing I'm trying out :)
Always considered git-lfs the bare minimum of doing anything with git, but that's obv just me. I'll leave a note
